config/routes.rb
Rails.application.routes.draw do

  get 'destinations', to: 'pages#destinations'

  get 'packages', to: 'pages#packages'

  get 'error', to: 'pages#error'

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '*path', to: redirect('/error')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def destinations
  end

  def packages
  end

  def error
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scratch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render "shared/nav" %>


    <%= yield %>
  </body>
</html>

app/views/pages/destinations.html.erb
<body id="destinations_page">

  <h1>Destinations</h1>

  <div class="divother">
    
    <p>How wonderful of you to be perusing after all!</p>

    <p>Introducing 3 wonderful destination oppurtunities that will astound all the while leaving you penniless, unless of course you have mucho dinero my friend.
    </p>

      <ol>
      	<li>European Tour (A must if you must)</li>
      	<li>American Continent Coastline Tour (You never would have guessed it!)</li>
      	<li>World Ocean Tour (haha yeah, if you've seen one, you've seen 'em all, but don't take our word for it, book today!)</li>
      </ol>

      <p>Now jump on over to our 'Packages' page to see our pricing and to be truly wowwed indeed.</p>

  </div>

</body>

app/views/pages/error.html.erb
<h2>Missed it by a mile! Return to a linked page above and thank you for trying so hard :) </h2>

app/views/pages/home.html.erb
<body id="home_page">

  <h1>Cruise Home</h1>

   <div class="divother">
     <p>We will show you the world from our world so cruise home and stay put with us. Enjoy the wonders of the world from the ever changing yet constant seascapes peppered with "land-ho's" inbetween.
     </p>

     <p>Visit our additional pages to see where you can go and for how much. Peruse away our friendly amigo, and remember, stay here not long... We embark soon ;)
     </p>
     
   </div>



</body>

app/views/pages/packages.html.erb
<h1>Packages</h1>

<body id="packages_page">

	<div id="travel_packages">
		 <div class="options">
		 	<h2>European Tour</h2>
		 	<p>Travel the European Isles and stop in on the wonders of your heritage. Discover the other world that exists.</p>
		 	<br><br><br><br><br>
		 	<p>$5678.00 for 20 day trip!</p>
		 </div>
		 
		 <div class="options">
		 	<h2>American Continent Coastline Tour</h2>
		 	<p>Travel the amamazazing coastline of the American continent from a legal distance of 200 miles away!
		 	<p><span class="binoculars">**bring your binocs**</span></p>
		 	<p>Join us for the non-adventure of a lifetime!</p>

		 	<p>$6738.00 for 30 day trip!</p>
		 </div>
		 
		 <div class="options">
		 	<h2>World Ocean Tour</h2>
		 	<p>Travel all of the worlds oceans and see breathtaking views! Wake to water and sleep to water. Filtered drinking water provided.</p>
		 	<br><br><br><br>
		 	<p>$8943.00 for 55 day trip!</p>
		 </div>

	</div>

</body>

app/views/shared/_nav.html.erb
<div id="navbar">
	<%= link_to "Home", root_path %>
	<%= link_to "Destinations", destinations_path %>
	<%= link_to "Packages", packages_path %>
</div>